#library("treedataverse")
library("argparser") 
library("aplot")
#library("svglite")
library("ape") 
library("dplyr")
library("ggplot2") 
library("tidytree")
library("treeio") 
library("ggtree")
library("ggtreeExtra") 

# Parse command line arguments
p <- arg_parser("Draw tree from trycycler cluster, with cluster names, sequence lengths, and read depths")

p <- add_argument(p, "--input",
                  short = "-i",
                  help = "Newick file generated by trycycler", 
                  default = "contigs.newick")

p <- add_argument(p, "--output", 
                  short = "-o", 
                  default = "tree_cluster.png", 
                  help = "Output image file (PNG)")

argv <- parse_args(p)


# READFILE
newick <- read.newick(argv$input)

# GENERATE EMPTY DATAFRAME
metadata <- data.frame(old_label = vector(mode = "character"),
                       label = vector(mode = "character"),
                       cluster_name = vector(mode = "character"),
                       length = vector(mode = "integer"),
                       depth = vector(mode = "numeric"))

# EXTRACT DATA FROM TREE
label <- newick$tip.label
for (i in seq_along(label)) {
  item <- sapply(strsplit(label[i],"_"), function(x){
    old_label <- label[i]
    new_label <- paste(x[[2]], x[[3]], sep = "")
    cluster_name <- paste(x[[1]], x[[2]], sep = "_")
    length <- as.integer(x[length(x) - 2])
    tip_depth <- tail(x, n=1)
    depth <- as.numeric(substring(tip_depth, 1, nchar(tip_depth) - 1))
    output <- c(old_label, new_label, cluster_name, length, depth)
  })
  metadata[nrow(metadata) + 1, ] <- item
}
metadata <- transform(metadata, length = as.integer(length),
                      depth = as.integer(depth))

# RENAME TIP LABEL AND MERGE DATA INTO TREE
tree <- rename_taxa(newick, metadata, old_label, label)
drops <- c("old_label")
tree_data <- metadata[ , !(names(metadata) %in% drops)]
p <- ggtree(tree) %<+% tree_data


# DRAW TREE
g <- p + geom_tiplab(#offset = .005,
                     #hjust = 0.005,
                     #align=TRUE,
                     size = 3.2) +
  geom_tippoint(aes(shape = cluster_name, color = cluster_name)) + 
  theme(legend.position = "right") + 
  theme_tree2()

# DRAW BUBBLES
p2 <- ggplot(tree_data, aes(x=0, y = label, label=length)) + 
  geom_point(aes(size = length, fill = depth), alpha = 0.9, shape = 21) +
  geom_text(hjust=-0.5, vjust=0.5, size=2) +
  scale_size(trans = "log10") +
  scale_fill_gradient(low = "white", high = "blue") +
  theme(axis.title = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.text = element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        plot.background=element_blank(),
  )

# CREATE COMPOSITE GRAPH
p2 %>% insert_left(g, width = 2)

ggsave(argv$output, dpi = 300)